### PR TITLE
added note for mailinglist registration without a google account

### PR DESCRIPTION
**Pull request by ghost**
I thought this may be a valuable addition, as this method may be unknown to some
users.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
Hmm.  I'm not sure this is needed.

**Comment by ghost** [comment]
@ThomasAdam  do you think users know this already?

**Comment by nicm** [comment]
This should definitely not go on the website but in the README file for tmux.

**Comment by nicm** [comment]
I have added a line to README, thanks.

**Pull request closed without merging**
