### PR TITLE
Change doctype to html5 and fix indent

### PR DESCRIPTION
**Pull request by isqua**
See the [real diff](https://github.com/tmux/tmux.github.io/pull/3/files?w=0) (without spaces diff).

### CODE REVIEW

**Comment by isqua** [comment]
Btw, how about a little visual enhancement?
tmux

**Comment by nicm** [comment]
Sorry for the delay, I didn't notice your comments. I like it, but I don't want the screenshots above the text, the screenshots are not important. Also the first line of text is way too big, it is not a title.

**Comment by isqua** [comment]
@nicm, I see. May be you’ll merge this PR (if it’s ok)? And I send next PR with visuals anytime soon?

**Comment by nicm** [comment]
Well, I think this particular change is just churn if you are just changing whitespace.

**Pull request closed without merging**
